services:
    ezpublish.fieldType.sckenhancedselection:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\Type
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: sckenhancedselection}

    ezpublish.fieldType.sckenhancedselection.externalStorage:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\EnhancedSelectionStorage
        arguments:
            - "@ezpublish.fieldType.sckenhancedselection.storage_gateway"
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: sckenhancedselection}

    ezpublish.fieldType.indexable.sckenhancedselection:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\SearchField
        tags:
            - {name: ezpublish.fieldType.indexable, alias: sckenhancedselection}

    ezpublish.fieldType.form.fieldtype_handler.sckenhancedselection:
        class: Netgen\Bundle\EnhancedSelectionBundle\Form\FieldTypeHandler\EnhancedSelection
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: sckenhancedselection}
