parameters:
    ezpublish.search.legacy.gateway.criterion_handler.common.enhanced_selection.class: Netgen\Bundle\EnhancedSelectionBundle\Core\Search\Legacy\Content\Common\Gateway\CriterionHandler\EnhancedSelection

services:
    ezpublish.search.legacy.gateway.criterion_handler.common.enhanced_selection:
        parent: ezpublish.search.legacy.gateway.criterion_handler.field_base
        class: "%ezpublish.search.legacy.gateway.criterion_handler.common.enhanced_selection.class%"
        tags:
            - {name: ezpublish.search.legacy.gateway.criterion_handler.content}
            - {name: ezpublish.search.legacy.gateway.criterion_handler.location}
