parameters:
    ezpublish.fieldType.sckenhancedselection.converter.class: Netgen\Bundle\EnhancedSelectionBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\EnhancedSelectionConverter
    ezpublish.fieldType.sckenhancedselection.storage_gateway.class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\EnhancedSelectionStorage\Gateway\DoctrineStorage

services:
    ezpublish.fieldType.sckenhancedselection.converter:
        class: "%ezpublish.fieldType.sckenhancedselection.converter.class%"
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: sckenhancedselection, lazy: true, callback: "::create"}

    ezpublish.fieldType.sckenhancedselection.storage_gateway:
        class: "%ezpublish.fieldType.sckenhancedselection.storage_gateway.class%"
        arguments:
            - "@ezpublish.api.storage_engine.legacy.connection"
