services:
    ezpublish.fieldType.sckenhancedselection.converter:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\EnhancedSelectionConverter
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: sckenhancedselection, lazy: true, callback: "::create"}

    ezpublish.fieldType.sckenhancedselection.storage_gateway:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\EnhancedSelectionStorage\Gateway\DoctrineStorage
        arguments:
            - "@ezpublish.api.storage_engine.legacy.connection"
