services:
    netgen.enhanced_selection.templating.twig.extension:
        class: Netgen\Bundle\EnhancedSelectionBundle\Templating\Twig\NetgenEnhancedSelectionExtension
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.translation_helper"
        tags:
            - { name: twig.extension }
